server:
  port: 9527

spring:
  profiles.active: test
  application:
    name: "fqLTS_${spring.profiles.active:test}"
  cloud:
    service-registry.auto-registration.enabled: false
    nacos:
      config:
        server-addr: localhost:8848
        namespace: ${spring.profiles.active}
    openfeign:
      client:
        config:
          # 全局默认配置
          default:
            # 读取超时时间
            readTimeout: 5000
            # 连接超时时间
            connectTimeout: 5000
  config.import:
    - nacos:fqLTS.yml

##  数据库相关
datasource.mysql:
  jdbc-url: *
  username: *
  password: *

datasource.hive:
  jdbc-url: *
  username: *
  password: *
  maximum-pool-size: 20

##  Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: healthcheck
      cors:
        allowed-origins: 'http://127.0.0.1:9527'
  endpoint:
    shutdown:
      access: unrestricted


logging.config: classpath:log/logback_dev.xml


--- #生产环境配置

spring:
  config.activate.on-profile: prod
logging.config: classpath:log/logback_prod.xml

