server:
  port: 9528

spring:
  profiles.active: test
  application:
    name: order
  cloud:
    #    service-registry.auto-registration.enabled: false
    nacos:
      config:
        server-addr: localhost:8848
        namespace: ${spring.profiles.active}
  config.import:
    - nacos:order.yml



